# Generated by Django 4.2.5 on 2023-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='etudiant_id',
            field=models.CharField(default='some_default_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='moyenne',
            field=models.FloatField(),
        ),
    ]
