# Generated by Django 4.2.5 on 2023-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_etudiant_etudiant_id_alter_etudiant_moyenne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='etudiant_id',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
