# Generated by Django 4.2.5 on 2023-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_remove_etudiant_etudiant_id_alter_etudiant_moyenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='cin',
            field=models.CharField(default='DEFAULT_VALUE', max_length=20),
        ),
    ]
