# Generated by Django 4.2.5 on 2023-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_etudiant_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='rang',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
